### ISSUE TITLE
Integrate MEMR protocol into NEL

### ISSUE THREAD

**Issue by HeinzLabPurdue** [HeinzLabPurdue/NEL#3]

**Comment by hausersn1** [comment]
- [ ] Set up default hardware with appropriate circuit file. 
- [ ] Create GUI for plotting MEMR while it runs 
- [ ] Add button to NEL main screen
- [ ] Write up notes for integrating additional features

**Comment by HeinzLabPurdue** [comment]
AS and MH began the setup for WBMEMR in NEL 1. Getting close, but still need to put together GUI and get it to all run from NEL. So close!!!!!!
